### ISSUE TITLE
ERDを作成する

### ISSUE THREAD

**Issue by norotime** [kenjikihara/repibo#21]
@kenjikihara こちらの通りに作成をしてください。設計プロセスが現時点で抜けてしまっていると面接時に話せないと思います。
http://it-koala.com/entity-relationship-diagram-1897

**Comment by kenjikihara** [comment]
@norotime 作成したERDと画面遷移図はどのような形でアップすればよいでしょうか？

**Comment by norotime** [comment]
@kenjikihara 画面遷移図は、Googleのリンク等で共有をお願いします。

**Comment by kenjikihara** [comment]
@norotime ERDを作成しました。ご確認よろしくお願いします！
https://drive.google.com/file/d/1DzNDisBHyV1GZc0Z8M6UNEpl7owA2KuS/view?usp=sharing

**Comment by norotime** [comment]
@kenjikihara 良いと思います！
