### ISSUE TITLE
画面遷移図とURL設計を作成する

### ISSUE THREAD

**Issue by norotime** [kenjikihara/repibo#22]
@kenjikihara 現時点のもので良いので作成してみましょう。

**Comment by kenjikihara** [comment]
@norotime 画面遷移図/URL設計を作成しました。ご確認よろしくお願いします！
https://drive.google.com/file/d/1LmKfsdkESOXXnFiDMbucPp7eMjLOemvq/view?usp=sharing

**Comment by norotime** [comment]
@kenjikihara 良いと思います！今後、開発拡張する場合は、設計図を書いてからにしましょう！

**Comment by kenjikihara** [comment]
@norotime ありがとうございます！了解しました！
